### ISSUE TITLE
Bug: bpfd crashes when you unload and then reload the same program

### ISSUE THREAD

**Issue by nerdalert** [redhat-et/bpfd#141]
I am hitting a scenario on main that bpfd panics when reloading a previously unloaded program.

Steps to recreate:
1. Install with `sudo ./scripts/setup.sh install`
2. start bpfd w/ `sudo ./target/debug/bpfd`
3. Load a program `sudo ./target/debug/bpfctl load --iface eth0 --priority 100 --section-name xdp --program-type xdp ../xdp-tutorial/basic01-xdp-pass/xdp_pass_kern.o`
4. Unload the program `sudo ./target/debug/bpfctl unload --iface eth0 421db4eb-9c6c-42b2-8f8b-5fb9bd21be92`
5. Load the same program again `sudo ./target/debug/bpfctl load --iface eth0 --priority 100 --section-name xdp --program-type xdp ../xdp-tutorial/basic01-xdp-pass/xdp_pass_kern.o`
6. Observe bpfd panic
7. Try and restart bpfd again and it continues to panic (unless the host restarts).

Workaround - Rebooting the host will allow for bpfd to start again.

Once we resolve this, I will add it to IT.

- bpfctl output

```
### Load the xdp pass program ###
[fedora@ip-172-31-93-116 bpfd]$ sudo ./target/debug/bpfctl load --iface eth0 --priority 100 --section-name xdp --program-type xdp ../xdp-tutorial/basic01-xdp-pass/xdp_pass_kern.o
421db4eb-9c6c-42b2-8f8b-5fb9bd21be92
[fedora@ip-172-31-93-116 bpfd]$ sudo ./target/debug/bpfctl list --iface eth0
eth0
xdp_mode: skb

0: 421db4eb-9c6c-42b2-8f8b-5fb9bd21be92
	section-name: "xdp"
	priority: 100
	path: ../xdp-tutorial/basic01-xdp-pass/xdp_pass_kern.o
	proceed-on:

### Unload the program ###
[fedora@ip-172-31-93-116 bpfd]$ sudo ./target/debug/bpfctl unload --iface eth0 421db4eb-9c6c-42b2-8f8b-5fb9bd21be92

### Try and load the program again ###
[fedora@ip-172-31-93-116 bpfd]$ sudo ./target/debug/bpfctl load --iface eth0 --priority 100 --section-name xdp --program-type xdp ../xdp-tutorial/basic01-xdp-pass/xdp_pass_kern.o
Error: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
```

-bpfd output (bpfd exits)

```
### bpfd panics when the program is installed for the 2nd time ###
[fedora@ip-172-31-93-116 bpfd]$ sudo ./target/debug/bpfd
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SyscallError { call: "bpf_link_create", io_error: Os { code: 16, kind: ResourceBusy, message: "Device or resource busy" } }', bpfd/src/server/bpf.rs:458:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Try and restart bpfd ###
sudo ./target/debug/bpfd
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', bpfd/src/server/bpf.rs:158:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Ty!

**Comment by nerdalert** [comment]
Looks like you need to delete the dispatcher link as well as the link_uuid in the dispatcher dir to avoid a file not found at restart:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', bpfd/src/server/bpf.rs:185:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Workaround:

```
sudo rm /var/run/bpfd/fs/dispatcher_2_0_link
sudo rm /var/run/bpfd/fs/dispatcher_2_0/link_1502db48-bc1e-4fe8-a8fe-44cc7d278ae7
```

Will work on a patch, ty.
