### ISSUE TITLE
bpfd container produces `ENOENT` error

### ISSUE THREAD

**Issue by nak3** [redhat-et/bpfd#198]
### Description

When running bpfd contains, it alwasy produces `ENOENT` error.
This is because nix's `from_uid()` calls `getpwnam_r()` but scratch image does not have any name service like `/etc/passwd` so it returns error.

In fact, if I run the command with `-v /etc/passwd:/etc/passwd` the error is gone.

### Step to reproduce

Just follow https://github.com/redhat-et/bpfd/blob/main/docs/developer/image-build.md#bpfd-1
The following error is produced wen running the command:

```
$ sudo podman run --init --privileged --net=host -v /etc/bpfd/certs/:/etc/bpfd/certs/ -v /sys/fs/bpf:/sys/fs/bpf quay.io/bpfd/bpfd:mainain
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ENOENT', bpfd/src/main.rs:121:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ENOENT', bpfd/src/main.rs:121:40
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ENOENT', bpfd/src/main.rs:121:40
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ENOENT', bpfd/src/main.rs:121:40
thread 'tokio-runtime-worker' panicked at 'thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ENOENT', bpfd/src/main.rs:121:40
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ENOENT', bpfd/src/main.rs:121:40
called `Result::unwrap()` on an `Err` value: ENOENT', bpfd/src/main.rs:121:40
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ENOENT', bpfd/src/main.rs:121:40
 ...
```

**Comment by nak3** [comment]
Closing as https://github.com/redhat-et/bpfd/commit/77a660ab3d86e841a9a714254e79b8dddb7808d9 fixed this.
